import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Nav";
import "bootstrap/dist/css/bootstrap.min.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="container">
          <div className="row">
            <div className="col-md-3">
              <Navigation />
            </div>
            <div className="col-md-9 pt-4">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
